version: '3'

services:
  payload:
    build: .
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo/cheatsheets
    healthcheck:
      test: 'wget -qO- http://127.0.0.1:3000/'
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    healthcheck:
      disable: true

volumes:
  data:
